extends SceneTree

# 测试入口：godot --headless --path . --script res://tests/run_tests.gd
# 每个被测模块一个 test_*.gd，失败会明确列出，不会静默跳过

const TCombat := preload("res://tests/test_combat.gd")
const TSpawner := preload("res://tests/test_spawner.gd")
const TEconomy := preload("res://tests/test_economy.gd")
const TInventory := preload("res://tests/test_inventory.gd")
const TBalance := preload("res://tests/test_balance.gd")
const TMovement := preload("res://tests/test_movement.gd")
const TWeapon := preload("res://tests/test_weapon.gd")
const TMelee := preload("res://tests/test_melee.gd")
const THit := preload("res://tests/test_hit.gd")
const TWok := preload("res://tests/test_wok.gd")
const TPickup := preload("res://tests/test_pickup.gd")
const TDash := preload("res://tests/test_dash.gd")
const TCharacter := preload("res://tests/test_character.gd")
const TLevel := preload("res://tests/test_level.gd")
const TDifficulty := preload("res://tests/test_difficulty.gd")
const TSave := preload("res://tests/test_save.gd")
const TRun := preload("res://tests/test_run.gd")
const TBgm := preload("res://tests/test_bgm.gd")
const TGamepad := preload("res://tests/test_gamepad.gd")
const TShopTiers := preload("res://tests/test_shop_tiers.gd")
const TStats := preload("res://tests/test_stats.gd")
const TOrientation := preload("res://tests/test_orientation.gd")
const THudLayout := preload("res://tests/test_hud_layout.gd")
const TCamLimits := preload("res://tests/test_cam_limits.gd")
const TShopPlan := preload("res://tests/test_shop_plan.gd")
const TPerfGuard := preload("res://tests/test_perf_guard.gd")
const THitFeel := preload("res://tests/test_hit_feel.gd")
const TWeaponSets := preload("res://tests/test_weapon_sets.gd")
const TShopFeedback := preload("res://tests/test_shop_feedback.gd")
const TArtIcons := preload("res://tests/test_art_icons.gd")
const TSynergy := preload("res://tests/test_synergy.gd")
const TCharBuild := preload("res://tests/test_char_build.gd")
const TCharIdentity := preload("res://tests/test_char_identity.gd")
const TDotThrottle := preload("res://tests/test_dot_throttle.gd")
const TSynergyBar := preload("res://tests/test_synergy_bar.gd")
const TSkillForms := preload("res://tests/test_skill_forms.gd")
const TWaveResult := preload("res://tests/test_wave_result.gd")
const TCharDetail := preload("res://tests/test_char_detail.gd")
const TCharUnlock := preload("res://tests/test_char_unlock.gd")
const TWeaponInfo := preload("res://tests/test_weapon_info.gd")
const TUnlockTree := preload("res://tests/test_unlock_tree.gd")
const TShopAI := preload("res://tests/test_shop_ai.gd")
const DataScript := preload("res://autoload/Data.gd")

var passed := 0
var failed := 0
var failures: Array = []

func _initialize() -> void:
	var data = DataScript.new()
	data.load_all()
	print("")
	print("=== veggie-arena 单元测试 ===")
	print("数据表: balance=%d 武器=%d 敌人=%d 强化=%d" % [
		data.balance.size(), data.weapons.size(),
		data.enemies.size(), data.upgrades.size()])

	_run("Combat", TCombat)
	_run("Spawner", TSpawner)
	_run("Economy", TEconomy)
	_run("Inventory", TInventory)
	_run("Balance(配平)", TBalance, data)
	_run("Movement(手感)", TMovement, data)
	_run("Weapon(武器)", TWeapon, data)
	_run("Melee(近战)", TMelee, data)
	_run("Hit(命中/分离)", THit, data)
	_run("Wok(锅气)", TWok, data)
	_run("Pickup(金币磁吸)", TPickup, data)
	_run("Dash(冲刺闪避)", TDash, data)
	_run("Character(角色)", TCharacter, data)
	_run("Level(经验/等级)", TLevel, data)
	_run("Difficulty(难度曲线守卫)", TDifficulty, data)
	_run("Save(存档/解锁)", TSave, data)
	_run("Run(通关)", TRun, data)
	_run("BGM(背景乐)", TBgm)
	_run("Gamepad(手柄)", TGamepad)
	_run("ShopTiers(武器分级商店)", TShopTiers)
	_run("Stats(属性目录)", TStats, data)
	_run("Orientation(横屏竞技场)", TOrientation, data)
	_run("HudLayout(顶部 HUD 不重叠)", THudLayout, data)
	_run("SynergyBar(羁绊条不压玩家/已接线)", TSynergyBar, data)
	_run("CamLimits(相机跟随/防黑边)", TCamLimits, data)
	_run("ShopPlan(商店节奏/单卡可控)", TShopPlan, data)
	_run("PerfGuard(帧率自适应降级)", TPerfGuard, data)
	_run("HitFeel(命中顿帧节流)", THitFeel, data)
	_run("WeaponSets(套装/属性缩放)", TWeaponSets, data)
	_run("ShopFeedback(商店三项修复)", TShopFeedback)
	_run("ArtIcons(武器图标齐全性)", TArtIcons, data.weapons)
	_run("Synergy(角色×武器×技能羁绊)", TSynergy, data)
	_run("CharBuild(每角色独占一条build)", TCharBuild, data)
	_run("CharIdentity(杂食线/命中DoT/开局充能)", TCharIdentity, data)
	_run("DotThrottle(持续伤害节流)", TDotThrottle, data)
	_run("SkillForms(技能形态变体/C3)", TSkillForms, data)
	_run("WaveResult(每波结算统计)", TWaveResult)
	_run("CharDetail(角色详情页内容齐全)", TCharDetail, data)
	_run("CharUnlock(角色解锁阶梯)", TCharUnlock, data)
	_run("WeaponInfo(武器详情页/候选池)", TWeaponInfo, data)
	_run("UnlockTree(选角排序/关系树)", TUnlockTree, data)
	_run("ShopAI(模拟AI购物策略)", TShopAI, data)

	# Data 是 Node，不会自动释放，避免退出时的 ObjectDB 泄漏警告
	data.free()

	print("")
	print("通过 %d / 失败 %d" % [passed, failed])
	if failed > 0:
		print("")
		print("失败明细：")
		for f in failures:
			print("  ✗ " + str(f))
		quit(1)
	else:
		print("=== 全部通过 ===")
		quit(0)

func _run(name: String, script, arg = null) -> void:
	var t = script.new()
	print("")
	print("-- " + name + " --")
	var r = t.run(arg) if arg != null else t.run()
	passed += int(r.get("pass", 0))
	failed += int(r.get("fail", 0))
	for f in r.get("failures", []):
		failures.append(name + ": " + str(f))
